[package]
name = "lunatic-log"
version = "0.1.0"
edition = "2021"
description = "A logging library for lunatic Rust applications"
repository = "https://github.com/lunatic-solutions/logger-rs"
categories = ["wasm", "logger", "log"]
license = "Apache-2.0/MIT"
readme = "Readme.md"


[dependencies]
lunatic = "^0.10"
serde = { version = "1.0", features = ["derive"] }
